name: Fetch and Filter Sources

on:
  workflow_dispatch:

jobs:
  fetch_sources:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with PAT
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MIHON }}  # ✅ force it to use PAT instead of GITHUB_TOKEN

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Fetch and extract sources
        run: |
          import json, requests
          url = "https://raw.githubusercontent.com/keiyoushi/extensions/refs/heads/repo/index.min.json"
          data = requests.get(url).json()
          sources = [src for item in data for src in item.get("sources", [])]
          with open("index.min.json", "w", encoding="utf-8") as f:
              json.dump(sources, f, separators=(",", ":"))
        shell: python

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add index.min.json
          git commit -m "Update index.min.json with only sources [bot]" || echo "No changes to commit"
          git push origin HEAD
